### ISSUE TITLE
🚑 Dev db, deploy db 중 한가지만 사용하도록 설정

### ISSUE THREAD

**Issue by can019** [probrainteam/circles-server-node#31]
# description
- 현재 dev db deploy db 중 dev db만 뜨도록 설정
- 분리 실행을 위한 script 작성 및 명령어 작성 필요
# Todo
* [x] run.sh 수정
* [x] package.json script 작성
* [x] local에서 확인
* [ ] Github Action에서 확인
