### ISSUE TITLE
🙏🏻 PM2를 통한 Node 구동

### ISSUE THREAD

**Issue by can019** [probrainteam/circles-server-node#55]
# description
 로드밸런싱을 위한 PM2 도입이 필요합니다.
# Todo
* [ ] pm2로 config 작성
* [ ] pm2로 node 구동
* [ ] docker pm2 구동 확인

**Comment by can019** [comment]
## Docker 내부에서 cluster 동작 시 에러 로깅, 트래픽 확인 등 시스템 추적이 어려움

nginx + docker로 로드 밸런싱 vs pm2 node로 로드 밸런싱을 유지하는 것 둘 중 하나를 선택해야함.

현재 circles-server-node는 docker container를 사용하고 있으므로 추 후 nginx를 통한 로드밸런싱을 진행 할 예정



### 참고자료
- https://dev.to/mandraketech/pm2-and-docker-in-the-world-of-nodejs-1lg8
- https://jywork.tistory.com/m/47
- https://stackoverflow.com/questions/51191378/what-is-the-point-of-using-pm2-and-docker-together
- https://m.clien.net/service/board/cm_app/13584078
- https://medium.com/beyond-coding/take-advantage-of-node-js-cluster-and-child-processes-with-pm2-rabbitmq-redis-and-nginx-c83eccfb8af8
